---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.onepassword.svc.cluster.local:8443
      vaults:
        HomeLab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: onepassword
