---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
  labels:
    app: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: grafana_oidc_${ENVIRONMENT}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: grafana_oidc_${ENVIRONMENT}
        property: client_secret
