apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - external-secret-slack.yaml
  - external-secret-oidc.yaml
  - helmrelease.yaml
  - httproute.yaml
  - prometheusrule-custom.yaml
  - podmonitor-flux.yaml
  - servicemonitor-gatus.yaml
  - servicemonitor-cloudflared.yaml
  - servicemonitor-falco.yaml
  - servicemonitor-authentik.yaml
  - dashboards
