---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - freshrss-default-deny.yaml
  - freshrss-allow.yaml
  - freshrss-cnpg-allow.yaml
  - freshrss-dump-allow.yaml
  - authentik-default-deny.yaml
  - authentik-allow.yaml
  - authentik-cnpg-allow.yaml
  - authentik-dump-allow.yaml
  - homer-default-deny.yaml
  - homer-allow.yaml
  - gatus-default-deny.yaml
  - gatus-allow.yaml
  - gatus-cnpg-allow.yaml
  - gatus-dump-allow.yaml
  - cloudflared-default-deny.yaml
  - cloudflared-allow.yaml
  - kromgo-default-deny.yaml
  - kromgo-allow.yaml
