---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-db-creds
  namespace: gatus
  labels:
    app.kubernetes.io/name: gatus
    component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: gatus_${ENVIRONMENT}
        property: username
    - secretKey: password
      remoteRef:
        key: gatus_${ENVIRONMENT}
        property: password
