---
apiVersion: v1
kind: Namespace
metadata:
  name: gatus
  labels:
    app: gatus
    env: ${ENVIRONMENT}
    owner: ${OWNER}
    th0th.dev/policy-target: application
    pod-security.kubernetes.io/enforce: restricted
