---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-db-creds
  namespace: freshrss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: username
    - secretKey: password
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: password
    - secretKey: database
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: database
    - secretKey: host
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: server
    - secretKey: port
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: port
    - secretKey: admin_user
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: admin_password
    - secretKey: admin_email
      remoteRef:
        key: freshrss_${ENVIRONMENT}_db
        property: admin_email
